const GovDel = {
    Ariana: ['Ariana Ville',
            'Ettadhamen',
            'Kalâat el-Andalous',
            'La Soukra',
            'Mnihla',
            'Raoued',
            'Sidi Thabet'],
    Béja: ['Amdoun', 'Béja Nord', 'Béja Sud','Goubellat','Medjez el-Bab','Nefza','Téboursouk','Testour','Thibar'],
    Ben_Arous: ['Ben Arous','Bou Mhel el-Bassatine', 'El Mourouj', 'Ezzahra', 'Fouchana', 'Hammam Chott', 'Hammam Lif', 'Medina Jedida','Mégrine','Mohamedia','Mornag','Radès'],
    Bizerte: ['Bizerte Nord', 'Bizerte Sud', 'El Alia', 'Ghar El Melh','Ghezala',
                                                'Joumine',
                                                'Mateur',
                                                'Menzel Bourguiba',
                                                'Menzel Jemil',
                                                'Ras Jebel',
                                                'Sejnane',
                                                'Tinja',
                                                'Utique',
                                                'Zarzouna'],
    Gabès: ['El Hamma',
            'Gabès Médina',	
            'Gabès Ouest',	
            'Gabès Sud',	
            'Ghannouch',	
            'Mareth',	
            'Matmata',	                                                            
            'Menzel El Habib',	
            'Métouia',	
            'Nouvelle Matmata'],
    Gafsa: ['Belkhir',	
            'El Guettar',	
            'El Ksar',	
            'Gafsa Nord',	                                                                    
            'Gafsa Sud',	
            'Mdhilla',	
            'Métlaoui',	
            'Moularès',	
            'Redeyef',	
            'Sened'],
    Jendouba: ['Sidi Aïch	Aïn Draham',
                'Balta-Bou Aouane',
                'Bou Salem',
                'Fernana',
                'Ghardimaou',
                'Jendouba Nord',
                'Jendouba Sud',
                'Oued Meliz',
                'Tabarka'],
    Kairouan: ['Bou Hajla',
                'Chebika',
                'Echrarda',
                'El Alâa',
                'Haffouz',
                'Hajeb El Ayoun',
                'Kairouan Nord',
                'Kairouan Sud',
                'Nasrallah',
                'Oueslatia',
                'Sbikha'],
    Kasserine: ['El Ayoun',
                'Ezzouhour',
                'Fériana',
                'Foussana',
                'Haïdra',                                                                
                'Hassi El Ferid',
                'Jedelienne',
                'Kasserine Nord',
                'Kasserine Sud',
                'Majel Bel Abbès',
                'Sbeïtla',
                'Sbiba',
                'Thala'],
    Kébili: ['Douz Nord',
            'Douz Sud',
            'Faouar',
            'Kébili Nord',
            'Kébili Sud',
            'Souk Lahad'],
     Manouba: ['Borj El Amri',
                'Djedeida',
                'Douar Hicher',
                'El Batan',
                'La Manouba',
                'Mornaguia',
                'Oued Ellil',
                'Tebourba'],
    Mahdia: ['Bou Merdes',
            'Chebba',
            'Chorbane',
            'El Jem',
            'Essouassi',
            'Hebira',
            'Ksour Essef',
            'Mahdia',
            'Melloulèche',
            'Ouled Chamekh',
            'Sidi Alouane'],
    Médenine: ['Ben Gardane',
                'Beni Khedache',
                'Djerba - Ajim',
                'Djerba - Houmt Souk',
                'Djerba - Midoun',
                'Médenine Nord',
                'Médenine Sud',
                'Sidi Makhlouf',
                'Zarzis'],
    Monastir: ['Bekalta',
                'Bembla',
                'Beni Hassen',
                'Jemmal',
                'Ksar Hellal',
                'Ksibet el-Médiouni',
                'Moknine',
                'Monastir',
                'Ouerdanine',
                'Sahline',
                'Sayada-Lamta-Bou Hajar',
                'Téboulba',
                'Zéramdine'],
    Nabeul: ['Béni Khalled',
            'Béni Khiar',
            'Bou Argoub',
            'Dar Chaâbane El Fehri',
            'El Haouaria',
            'El Mida',
            'Grombalia',
            'Hammam Ghezèze',
            'Hammamet',
            'Kélibia',
            'Korba',
            'Menzel Bouzelfa',
            'Menzel Temime',
            'Nabeul',
            'Soliman',
            'Takelsa'],
    Sfax: ['Agareb',
            'Bir Ali Ben Khalifa',
            'El Amra',
            'El Hencha',
            'Graïba',
            'Jebiniana',
            'Kerkennah',
            'Mahrès',
            'Menzel Chaker',
            'Sakiet Eddaïer',
            'Sakiet Ezzit',
            'Sfax Ouest',
            'Sfax Sud',
            'Sfax Ville',
            'Skhira',
            'Thyna'],
    Sidi_Bouzid: ['Bir El Hafey',
                'Cebbala Ouled Asker',
                'Jilma',
                'Meknassy',
                'Menzel Bouzaiane',
                'Mezzouna',
                'Ouled Haffouz',
                'Regueb',
                'Sidi Ali Ben Aoun',
                'Sidi Bouzid Est',
                'Sidi Bouzid Ouest',
                'Souk Jedid'],
    Siliana: ['Bargou',
            'Bou Arada',
            'El Aroussa',                                                    
            'El Krib',
            'Gaâfour',
            'Kesra',
            'Makthar',
            'Rouhia',
            'Sidi Bou Rouis',
            'Siliana Nord',
            'Siliana Sud'],
    Sousse: ['Akouda',
            'Bouficha',
            'Enfida',
            'Hammam Sousse',
            'Hergla',                                                
            'Kalâa Kebira',
            'Kalâa Seghira',
            'Kondar',
            'Msaken',
            'Sidi Bou Ali',
            'Sidi El Hani',
            'Sousse Jawhara',
            'Sousse Médina',
            'Sousse Riadh',
            'Sousse Sidi Abdelhamid'],
    Tataouine: ['Bir Lahmar',                                
                'Dehiba',                                
                'Ghomrassen',
                'Remada',                                
                'Smâr',
                'Tataouine Nord',
                'Tataouine Sud'],
    Tozeur: ['Degache',
            'Hazoua',                                                    
            'Nefta',
            'Tameghza',                                                    
            'Tozeur'],
    Tunis: ['Bab El Bhar',
            'Bab Souika',
            'Carthage',
            'Cité El Khadra',
            'Djebel Jelloud',
            'El Kabaria',
            'El Menzah',
            'El Omrane',
            'El Omrane supérieur',
            'El Ouardia',
            'Ettahrir',
            'Ezzouhour',
            'Hraïria',
            'La Goulette',
            'La Marsa',
            'Le Bardo',
            'Le Kram',
            'Médina',
            'Séjoumi',
            'Sidi El Béchir',
            'Sidi Hassine'],
    Zaghouan: ['Bir Mcherga',
                'El Fahs',
                'Nadhour',
                'Saouaf',
                'Zaghouan',
                'Zriba'],
    Kef: ['Dahmani',
        'El Ksour',
        'Jérissa',
        'Kalâat Khasba',
        'Kalaat Senan',
        'Kef Est',
        'Kef Ouest',
        'Nebeur',
        'Sakiet Sidi Youssef',
        'Sers',
        'Tajerouine'],
  };

export default GovDel;